apiVersion: v1
kind: PersistentVolume
metadata:
  name: aegis-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/aegis"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aegis-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
